fix(clob): usage of ampersand before and without question mark (#189)
Two of the methods are using `&` without `?` in the urls. You can see
the GET urls and the problem.

Here are the errors:
`earnings_for_user_for_day`
```
Error: Status: error(405 Method Not Allowed) making GET call to /rewards/user&next_cursor=LTE= with

Caused by:
    error(405 Method Not Allowed) making GET call to /rewards/user&next_cursor=LTE= with
```

`current_rewards`
```
Error: Status: error(400 Bad Request) making GET call to /rewards/markets/current&next_cursor=NTAw with {"error":"Invalid market"}


Caused by:
    error(400 Bad Request) making GET call to /rewards/markets/current&next_cursor=NTAw with {"error":"Invalid market"}
```